name: sa7a7
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  


 
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  intl: ^0.19.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg_icons: ^0.0.1
  path:
  bloc_test: ^9.1.4
  responsive: ^0.3.11+11
  shared_preferences:
  carousel_slider:
  # fluttertoast: ^8.2.4
  path_provider: ^2.1.1
  extended_image: ^8.1.1
  flutter_svg: ^0.23.0+1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.20
  cloud_firestore: ^4.15.9
  awesome_dialog: ^3.2.0
  # google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:
  assets:
    - assets/images/
    - assets/icons/


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
