// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOyjC1vFGOlY1wscRJTc1zGx8CwT71yuU',
    appId: '1:853321173799:android:925b710dbaea0cc3203702',
    messagingSenderId: '853321173799',
    projectId: 'sa7a7-63405',
    storageBucket: 'sa7a7-63405.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzZ-cXPDagNyw9gm-gWyfNB3vZUPehAbw',
    appId: '1:853321173799:web:41fd64e2b5784c41203702',
    messagingSenderId: '853321173799',
    projectId: 'sa7a7-63405',
    authDomain: 'sa7a7-63405.firebaseapp.com',
    storageBucket: 'sa7a7-63405.appspot.com',
    measurementId: 'G-HGKTM09BWR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WLl1koezj8pVq8rIHA6Rb6JAU7FONCQ',
    appId: '1:853321173799:ios:55a132edfe697bce203702',
    messagingSenderId: '853321173799',
    projectId: 'sa7a7-63405',
    storageBucket: 'sa7a7-63405.appspot.com',
    iosClientId: '853321173799-10cnibfmef5rjop51v3n1fne0r8dkji1.apps.googleusercontent.com',
    iosBundleId: 'com.testTrake.manStest',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WLl1koezj8pVq8rIHA6Rb6JAU7FONCQ',
    appId: '1:853321173799:ios:55a132edfe697bce203702',
    messagingSenderId: '853321173799',
    projectId: 'sa7a7-63405',
    storageBucket: 'sa7a7-63405.appspot.com',
    iosClientId: '853321173799-10cnibfmef5rjop51v3n1fne0r8dkji1.apps.googleusercontent.com',
    iosBundleId: 'com.testTrake.manStest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzZ-cXPDagNyw9gm-gWyfNB3vZUPehAbw',
    appId: '1:853321173799:web:b94b855f82d0f521203702',
    messagingSenderId: '853321173799',
    projectId: 'sa7a7-63405',
    authDomain: 'sa7a7-63405.firebaseapp.com',
    storageBucket: 'sa7a7-63405.appspot.com',
    measurementId: 'G-MKV9C44F00',
  );

}